export const products = [
  {
    id: 1,
    title: 'ADORLY Low-Top Lace-Up Casual Shoes For Women',
    description: 'Beige in color',
    price: '760',
    img: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR-TKzAihzO7Gwwfd3AYwlkNEPysyT5btk-fmBN8wA--norlm_p74B0L8IMvOKJOJYXVbLorLjD13TU9dII-uphlAqIOexTFqhWPI5Ia3D0xgib79W-r_CTdg',
    quantity: 1,
  },
  {
    id: 2,
    title: 'Red Tape',
    description: 'Women Colorblock Multi Color Walking Shoes ',
    price: '2,009',
    img: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRfZ_wxw5X8N1-MPBnd3j34RNBTRHwatsg_MHn11MaqR4SCzNcWuj6TyEpdJFY7L_bTxctWARSBzCWdPGMtvSkCjmA7eZg-y0fXMj62dDcH',
    quantity: 1,
  },
  {
    id: 3,
    title: 'AfroJack',
    description: 'Women Pink Colourblocked Sneakers',
    price: '721',
    img: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQ0rleaIvoLL9eT0ESaMREtzNuyOSJ_RndUx9hwg0brmH8BvhsOv_d6L6fMVv0RH1y674l3g_iJQo8s_NPqZV982i9inh0UrLY7eYOVQxcwCedX403y-dSBlg',
    quantity: 1,
  },
  {
    id: 4,
    title: 'Bourge Womens Micam-z54 Running Shoes',
    description: 'Bourge Womens Micam-z54 Running Shoes',
    price: '608',
    img: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTQet14HYb9TLHUCVADujbU7m_zWiXorezoSIA-Efjs4APc2yAwhfCBQS5NSTtdm5Wi6FWPqSYSMyFYx6LCzdACm6muvhD_WRe4zWNKRu3wTZmWFMveJegZixI',
    quantity: 1,
  },
  {
    id: 5,
    title: 'Roadster',
    description: 'Women White & Teal Green Colourblocked Flatform Sneakers',
    price: '1049',
    img: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRzbw6y-pNC9rvnCQHMHAa-4LEKtfxg5FFR-ivHCqYmn7E8RNcEH0UChIBvFGWFXGg0jzzhP6Qz3Cqz6ZzudMHYDpnEKBZD9B3M350EZ00',
    quantity: 1,
  },
  {
    id: 6,
    title: 'Red Tape',
    description: 'Women White Sneakers',
    price: '1199',
    img: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQFyHOOGI0kknzUAWTlmKwuESx_jAvDvWPvx217OV7INDKv239kyUMDh33aZI3Q3BmIpx2As9wlQoF1Tn-YFSqQ5s9-sGXJ31O6DouI56Q',
    quantity: 1,
  },
  {
    id: 7,
    title: 'HRX by Hrithik Roshan',
    description: 'Women White Front Runner Shoes',
    price: '2049',
    img: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQyS8T0Ecshp9GP7sVeUyjIWXkMh_XB_kS7CiK1_1AiFihEfECfPIQSihH-7-UPEGXakSIeVFAm3g9SUQ63NHkT5FQxxbJDyNDUVICO60pV',
    quantity: 1,
  },
  {
    id: 8,
    title: 'El Paso',
    description: 'Women Black Solid Lightweight Sneakers',
    price: '838',
    img: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTavI6E3z8VGPx6UjDikPquk-OQq6FQ-ZBiHDYxvDGxAerOH9I2ixHePTUN-05IfFfxG1BwcokZRTx7YJukWV-fhyoYjJL5cgsoGKKQAGc',
    quantity: 1,
  },
  {
    id: 9,
    title: 'Campus',
    description: 'Women Black Mesh Running Shoes',
    price: '1099',
    img: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRM8SGd0MFuixZc--x8bphY2GqWi0Crm9Z7hbWvIDOzI2P80Swk5kGZaa9hg75xk7ydpbG_XPot-OBHoy28wLfEtZYP-5JuBbPq6IfBNp1wQyWoq4EcwGinWiA',
    quantity: 1,
  },
];
